server {
  listen 80;

  location /api/ {
    proxy_pass http://app:5000/api/;
  }

  location /uploads/ {
    proxy_pass http://app:5000/uploads/;
  }

  location / {
    proxy_pass http://app:5000/;
  }
}
